type token =
  | T_EOF
  | K_DEF of (Lexing.position)
  | K_CLASS of (Lexing.position)
  | K_MODULE of (Lexing.position)
  | K_CAST of (Lexing.position)
  | K_OR of (Lexing.position)
  | K_SELF of (Lexing.position)
  | T_BEGIN_LINE of (Lexing.position)
  | T_NEWLINE of (Lexing.position)
  | T_SEMICOLON of (Lexing.position)
  | T_COLON of (Lexing.position)
  | T_DOUBLE_COLON of (Lexing.position)
  | T_DOT of (Lexing.position)
  | T_STAR of (Lexing.position)
  | T_QUESTION of (Lexing.position)
  | T_CARROT of (Lexing.position)
  | T_BANG of (Lexing.position)
  | T_RARROW of (Lexing.position)
  | T_LPAREN of (Lexing.position)
  | T_RPAREN of (Lexing.position)
  | T_LESS of (Lexing.position)
  | T_GREATER of (Lexing.position)
  | T_COMMA of (Lexing.position)
  | T_LBRACKET of (Lexing.position)
  | T_RBRACKET of (Lexing.position)
  | T_LBRACE of (Lexing.position)
  | T_RBRACE of (Lexing.position)
  | T_SUBTYPE of (Lexing.position)
  | T_INST_VAR of (Lexing.position * string)
  | T_CONST_ID of (Lexing.position * string)
  | T_TYPE_ID of (Lexing.position * string)
  | T_METHOD_NAME of (Lexing.position * string)

val input :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Annotation.t option
