#!/usr/bin/env ruby

ROOT = File.expand_path("../..", __FILE__)
BIN = ROOT + "/gem_bin"
LIB = ROOT + "/lib"
DCONFIG = "#{ROOT}/druby.conf"
ENV['PATH'] = BIN + ":" + ENV['PATH']

exec("#{BIN}/druby.real",
  "--dr-config=#{DCONFIG}",
  "-I#{LIB}",
  *ARGV)
